In [1]:
import numpy as np


In [2]:
arr1 = np.array([1, 2, 3, 4, 5])  
arr2 = np.array([[1, 2, 3], [4, 5, 6]]) 
print(arr1) 
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [5]:
arr3=np.zeros(5)
print(arr3)

[0. 0. 0. 0. 0.]


In [7]:
arr4=np.zeros((5,4))
print(arr4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
arr5=np.zeros((5,4,3))
print(arr5)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [12]:
arr5=np.ones((5,4,3))
print(arr5)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [15]:
np.arange(1,11)   #can not be used for 2d array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
arr6=np.linspace(1,10,5)

In [21]:
print(arr6)

[ 1.    3.25  5.5   7.75 10.  ]


In [22]:
arr3.ndim

2

In [23]:
arr3.shape

(5, 4)

In [24]:
arr3.size

20

In [25]:
print(arr3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [26]:
arr3.dtype

dtype('float64')

In [27]:
list1=[1,2,33,4,5,6]

In [28]:
arraylist=np.array(list1)

In [29]:
print(arraylist)

[ 1  2 33  4  5  6]
