In [44]:
import numpy as np


In [45]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [46]:
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [47]:
arr[1,0,1]

np.int64(8)

In [48]:
print(arr[1,0,1])

8


In [49]:
print(arr)
print("____________________________________")
print(arr**2)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
____________________________________
[[[  1   4   9]
  [ 16  25  36]]

 [[ 49  64  81]
  [100 121 144]]]


In [50]:
arr1=np.array([1,2,3,4,5])


In [51]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [52]:
print(arr1*arr2)

[[ 1  4  9 16 25]
 [ 6 14 24 36 50]]


In [53]:
arr4=np.array([12,43,1,2,4,1,3,5,6,3,5,7,65,4,77,90])

In [54]:
print(arr4.size)

16


In [55]:
print(arr4.reshape(4,4))

[[12 43  1  2]
 [ 4  1  3  5]
 [ 6  3  5  7]
 [65  4 77 90]]


In [56]:
print(arr4.reshape(2,2,4))

[[[12 43  1  2]
  [ 4  1  3  5]]

 [[ 6  3  5  7]
  [65  4 77 90]]]


In [57]:
print(arr4.resize(4,4))

None


In [58]:
marks=np.array([13,45,76,57,98])

In [59]:
grades=np.where(marks>=75,"A",
np.where(marks>=55,"B",
np.where(marks>=40,"C",
np.where(marks>=20,"D" ,"fail"))))

In [60]:
grades

array(['fail', 'C', 'A', 'B', 'A'], dtype='<U4')

In [61]:
marks

array([13, 45, 76, 57, 98])

In [62]:
print(marks>60)

[False False  True False  True]


In [63]:
print(marks[marks>60])

[76 98]


In [64]:
print(marks[(marks>60) & (marks<80)])

[76]


In [65]:
np.mean(marks)

np.float64(57.8)

In [66]:
np.median(marks)

np.float64(57.0)

In [67]:
np.std(marks)

np.float64(28.70121948628664)

In [72]:
%timeit arr1*2

1.49 μs ± 306 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [73]:
%timeit [i*2 for i in arr1]

1.57 μs ± 70.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [74]:
print(np.max(arr1))

5


In [75]:
print(np.min(arr1))

1
